### ISSUE TITLE
when switch prefix, the behaviour inconsistent

### ISSUE THREAD

**Issue by snowman** [SpringHan/minibuffer-modifier-keys#1]
Steps to reproduce:

1. `M-x` `SPC` `SPC` activate "keypad-mode"
2. `.` switch to `M-` prefix
3. Then use `n` or `p` you can run `next-history-element` or `previous-history-element` to select minibuffer history item. 

#### But how to use `M-.`?

I come out two solutions:

1. `M-x` `SPC` `SPC` `.` `.` (it shows `[M-M-]`) then `.`
    => why NOT press 2 times of `.` instead 3 times of `.`? 
    => `M-M-` prefix make nonsense
2. `M-x` `SPC` `SPC` `.` `C-g` then `.`
    => Here you press 2 times of `.`

#### Expected
1. To run `M-.` press `M-x` `SPC` `SPC` `.` `.` should be enough.
2. Each of the three prefixes should be mutually excluded, you can only select one of them, meaning not able to combine them, and even not repeating self.
   => currently, `M-x` `SPC` `SPC` `.` `/` shows `M-C-M-`, which oneself may expect `M-/`
   => `M-x` `SPC` `SPC` `.` `.` shows `M-M-`, which oneself may expect `M-.`

**Comment by snowman** [comment]
Interestingly, 

```lisp
(eq (key-binding (kbd "C-C-f"))
    (key-binding (kbd "M-f")))
```

returns `t`

**Comment by SpringHan** [comment]
Sorry, maybe the document is not clearly.  
When you need to directly insert a character and the character is one of the three prefix.  
You can press `SPC` before press it.  
e.g.:  
 You want to use `M-.`. Firstly, you should make sure the current prefix is `M-`, then you just need to press: `SPC` `.`.

**Comment by snowman** [comment]
But `M-x` `SPC` `SPC` `.` `SPC` `.` shows `[M-SPC M-]`

**Comment by SpringHan** [comment]
Sorry, it's my mistake.  
You can get the lastest commit.  
When there's a prefix is exists, you can directly press any key and it'll not be convert to prefix.  
So, you just need: `M-x` `SPC` `SPC` `.` `.`

**Comment by snowman** [comment]
Thanks :heart:, it works like a charm, btw, the document is poor :sweat_smile:
